using System;
using System.Collections.Generic;
using System.Text;

namespace GFAssetLib.Object
{
    // version : 6
    // classID{74}: AnimationClip <- Motion <- NamedObject <- EditorExtension <- Object
    //AnimationClip Base // ByteOffset{0}, ByteSize{ffffffff}, Index{0}, IsArray{0}, MetaFlag{8000}
    //  string m_Name // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{2}, IsArray{1}, MetaFlag{4001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{3}, IsArray{0}, MetaFlag{1}
    //      char data // ByteOffset{ffffffff}, ByteSize{1}, Index{4}, IsArray{0}, MetaFlag{1}
    //  int m_AnimationType // ByteOffset{c0}, ByteSize{4}, Index{5}, IsArray{0}, MetaFlag{0}
    //  bool m_Compressed // ByteOffset{58}, ByteSize{1}, Index{6}, IsArray{0}, MetaFlag{10}
    //  bool m_UseHighQualityCurve // ByteOffset{59}, ByteSize{1}, Index{7}, IsArray{0}, MetaFlag{4010}
    //  vector m_RotationCurves // ByteOffset{60}, ByteSize{ffffffff}, Index{8}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{9}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{a}, IsArray{0}, MetaFlag{1}
    //      QuaternionCurve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{b}, IsArray{0}, MetaFlag{8001}
    //        AnimationCurve curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{c}, IsArray{0}, MetaFlag{1}
    //          vector m_Curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{d}, IsArray{0}, MetaFlag{1}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{e}, IsArray{1}, MetaFlag{1}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{f}, IsArray{0}, MetaFlag{1}
    //              Keyframe data // ByteOffset{ffffffff}, ByteSize{34}, Index{10}, IsArray{0}, MetaFlag{1}
    //                float time // ByteOffset{ffffffff}, ByteSize{4}, Index{11}, IsArray{0}, MetaFlag{1}
    //                Quaternionf value // ByteOffset{ffffffff}, ByteSize{10}, Index{12}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{13}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{14}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{15}, IsArray{0}, MetaFlag{200001}
    //                  float w // ByteOffset{ffffffff}, ByteSize{4}, Index{16}, IsArray{0}, MetaFlag{200001}
    //                Quaternionf inSlope // ByteOffset{ffffffff}, ByteSize{10}, Index{17}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{18}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{19}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{1a}, IsArray{0}, MetaFlag{200001}
    //                  float w // ByteOffset{ffffffff}, ByteSize{4}, Index{1b}, IsArray{0}, MetaFlag{200001}
    //                Quaternionf outSlope // ByteOffset{ffffffff}, ByteSize{10}, Index{1c}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{1d}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{1e}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{1f}, IsArray{0}, MetaFlag{200001}
    //                  float w // ByteOffset{ffffffff}, ByteSize{4}, Index{20}, IsArray{0}, MetaFlag{200001}
    //          int m_PreInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{21}, IsArray{0}, MetaFlag{1}
    //          int m_PostInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{22}, IsArray{0}, MetaFlag{1}
    //        string path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{23}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{24}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{25}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{26}, IsArray{0}, MetaFlag{1}
    //  vector m_CompressedRotationCurves // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{27}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{28}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{29}, IsArray{0}, MetaFlag{1}
    //      CompressedAnimationCurve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{2a}, IsArray{0}, MetaFlag{8001}
    //        string m_Path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{2b}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{2c}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{2d}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{2e}, IsArray{0}, MetaFlag{1}
    //        PackedBitVector m_Times // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{2f}, IsArray{0}, MetaFlag{8001}
    //          unsigned int m_NumItems // ByteOffset{ffffffff}, ByteSize{4}, Index{30}, IsArray{0}, MetaFlag{1}
    //          vector m_Data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{31}, IsArray{0}, MetaFlag{8001}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{32}, IsArray{1}, MetaFlag{4001}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{33}, IsArray{0}, MetaFlag{1}
    //              UInt8 data // ByteOffset{ffffffff}, ByteSize{1}, Index{34}, IsArray{0}, MetaFlag{1}
    //          UInt8 m_BitSize // ByteOffset{ffffffff}, ByteSize{1}, Index{35}, IsArray{0}, MetaFlag{4001}
    //        PackedBitVector m_Values // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{36}, IsArray{0}, MetaFlag{8001}
    //          unsigned int m_NumItems // ByteOffset{ffffffff}, ByteSize{4}, Index{37}, IsArray{0}, MetaFlag{1}
    //          vector m_Data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{38}, IsArray{0}, MetaFlag{c001}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{39}, IsArray{1}, MetaFlag{4001}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{3a}, IsArray{0}, MetaFlag{1}
    //              UInt8 data // ByteOffset{ffffffff}, ByteSize{1}, Index{3b}, IsArray{0}, MetaFlag{1}
    //        PackedBitVector m_Slopes // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{3c}, IsArray{0}, MetaFlag{8001}
    //          unsigned int m_NumItems // ByteOffset{ffffffff}, ByteSize{4}, Index{3d}, IsArray{0}, MetaFlag{1}
    //          float m_Range // ByteOffset{ffffffff}, ByteSize{4}, Index{3e}, IsArray{0}, MetaFlag{1}
    //          float m_Start // ByteOffset{ffffffff}, ByteSize{4}, Index{3f}, IsArray{0}, MetaFlag{1}
    //          vector m_Data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{40}, IsArray{0}, MetaFlag{8001}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{41}, IsArray{1}, MetaFlag{4001}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{42}, IsArray{0}, MetaFlag{1}
    //              UInt8 data // ByteOffset{ffffffff}, ByteSize{1}, Index{43}, IsArray{0}, MetaFlag{1}
    //          UInt8 m_BitSize // ByteOffset{ffffffff}, ByteSize{1}, Index{44}, IsArray{0}, MetaFlag{4001}
    //        int m_PreInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{45}, IsArray{0}, MetaFlag{1}
    //        int m_PostInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{46}, IsArray{0}, MetaFlag{1}
    //  vector m_PositionCurves // ByteOffset{70}, ByteSize{ffffffff}, Index{47}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{48}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{49}, IsArray{0}, MetaFlag{1}
    //      Vector3Curve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{4a}, IsArray{0}, MetaFlag{8001}
    //        AnimationCurve curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{4b}, IsArray{0}, MetaFlag{1}
    //          vector m_Curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{4c}, IsArray{0}, MetaFlag{1}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{4d}, IsArray{1}, MetaFlag{1}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{4e}, IsArray{0}, MetaFlag{1}
    //              Keyframe data // ByteOffset{ffffffff}, ByteSize{28}, Index{4f}, IsArray{0}, MetaFlag{1}
    //                float time // ByteOffset{ffffffff}, ByteSize{4}, Index{50}, IsArray{0}, MetaFlag{1}
    //                Vector3f value // ByteOffset{ffffffff}, ByteSize{c}, Index{51}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{52}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{53}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{54}, IsArray{0}, MetaFlag{200001}
    //                Vector3f inSlope // ByteOffset{ffffffff}, ByteSize{c}, Index{55}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{56}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{57}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{58}, IsArray{0}, MetaFlag{200001}
    //                Vector3f outSlope // ByteOffset{ffffffff}, ByteSize{c}, Index{59}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{5a}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{5b}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{5c}, IsArray{0}, MetaFlag{200001}
    //          int m_PreInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{5d}, IsArray{0}, MetaFlag{1}
    //          int m_PostInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{5e}, IsArray{0}, MetaFlag{1}
    //        string path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{5f}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{60}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{61}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{62}, IsArray{0}, MetaFlag{1}
    //  vector m_ScaleCurves // ByteOffset{80}, ByteSize{ffffffff}, Index{63}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{64}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{65}, IsArray{0}, MetaFlag{1}
    //      Vector3Curve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{66}, IsArray{0}, MetaFlag{8001}
    //        AnimationCurve curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{67}, IsArray{0}, MetaFlag{1}
    //          vector m_Curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{68}, IsArray{0}, MetaFlag{1}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{69}, IsArray{1}, MetaFlag{1}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{6a}, IsArray{0}, MetaFlag{1}
    //              Keyframe data // ByteOffset{ffffffff}, ByteSize{28}, Index{6b}, IsArray{0}, MetaFlag{1}
    //                float time // ByteOffset{ffffffff}, ByteSize{4}, Index{6c}, IsArray{0}, MetaFlag{1}
    //                Vector3f value // ByteOffset{ffffffff}, ByteSize{c}, Index{6d}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{6e}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{6f}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{70}, IsArray{0}, MetaFlag{200001}
    //                Vector3f inSlope // ByteOffset{ffffffff}, ByteSize{c}, Index{71}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{72}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{73}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{74}, IsArray{0}, MetaFlag{200001}
    //                Vector3f outSlope // ByteOffset{ffffffff}, ByteSize{c}, Index{75}, IsArray{0}, MetaFlag{200001}
    //                  float x // ByteOffset{ffffffff}, ByteSize{4}, Index{76}, IsArray{0}, MetaFlag{200001}
    //                  float y // ByteOffset{ffffffff}, ByteSize{4}, Index{77}, IsArray{0}, MetaFlag{200001}
    //                  float z // ByteOffset{ffffffff}, ByteSize{4}, Index{78}, IsArray{0}, MetaFlag{200001}
    //          int m_PreInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{79}, IsArray{0}, MetaFlag{1}
    //          int m_PostInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{7a}, IsArray{0}, MetaFlag{1}
    //        string path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{7b}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{7c}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{7d}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{7e}, IsArray{0}, MetaFlag{1}
    //  vector m_FloatCurves // ByteOffset{90}, ByteSize{ffffffff}, Index{7f}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{80}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{81}, IsArray{0}, MetaFlag{1}
    //      FloatCurve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{82}, IsArray{0}, MetaFlag{8001}
    //        AnimationCurve curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{83}, IsArray{0}, MetaFlag{1}
    //          vector m_Curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{84}, IsArray{0}, MetaFlag{1}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{85}, IsArray{1}, MetaFlag{1}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{86}, IsArray{0}, MetaFlag{1}
    //              Keyframe data // ByteOffset{ffffffff}, ByteSize{10}, Index{87}, IsArray{0}, MetaFlag{1}
    //                float time // ByteOffset{ffffffff}, ByteSize{4}, Index{88}, IsArray{0}, MetaFlag{1}
    //                float value // ByteOffset{ffffffff}, ByteSize{4}, Index{89}, IsArray{0}, MetaFlag{1}
    //                float inSlope // ByteOffset{ffffffff}, ByteSize{4}, Index{8a}, IsArray{0}, MetaFlag{1}
    //                float outSlope // ByteOffset{ffffffff}, ByteSize{4}, Index{8b}, IsArray{0}, MetaFlag{1}
    //          int m_PreInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{8c}, IsArray{0}, MetaFlag{1}
    //          int m_PostInfinity // ByteOffset{ffffffff}, ByteSize{4}, Index{8d}, IsArray{0}, MetaFlag{1}
    //        string attribute // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{8e}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{8f}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{90}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{91}, IsArray{0}, MetaFlag{1}
    //        string path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{92}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{93}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{94}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{95}, IsArray{0}, MetaFlag{1}
    //        int classID // ByteOffset{ffffffff}, ByteSize{4}, Index{96}, IsArray{0}, MetaFlag{1}
    //        PPtr<MonoScript> script // ByteOffset{ffffffff}, ByteSize{8}, Index{97}, IsArray{0}, MetaFlag{1}
    //          int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{98}, IsArray{0}, MetaFlag{1}
    //          int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{99}, IsArray{0}, MetaFlag{1}
    //  vector m_PPtrCurves // ByteOffset{a0}, ByteSize{ffffffff}, Index{9a}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{9b}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{9c}, IsArray{0}, MetaFlag{1}
    //      PPtrCurve data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{9d}, IsArray{0}, MetaFlag{8001}
    //        vector curve // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{9e}, IsArray{0}, MetaFlag{1}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{9f}, IsArray{1}, MetaFlag{1}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{a0}, IsArray{0}, MetaFlag{1}
    //            PPtrKeyframe data // ByteOffset{ffffffff}, ByteSize{c}, Index{a1}, IsArray{0}, MetaFlag{1}
    //              float time // ByteOffset{ffffffff}, ByteSize{4}, Index{a2}, IsArray{0}, MetaFlag{1}
    //              PPtr<Object> value // ByteOffset{ffffffff}, ByteSize{8}, Index{a3}, IsArray{0}, MetaFlag{1}
    //                int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{a4}, IsArray{0}, MetaFlag{1}
    //                int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{a5}, IsArray{0}, MetaFlag{1}
    //        string attribute // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{a6}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{a7}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{a8}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{a9}, IsArray{0}, MetaFlag{1}
    //        string path // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{aa}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{ab}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{ac}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{ad}, IsArray{0}, MetaFlag{1}
    //        int classID // ByteOffset{ffffffff}, ByteSize{4}, Index{ae}, IsArray{0}, MetaFlag{1}
    //        PPtr<MonoScript> script // ByteOffset{ffffffff}, ByteSize{8}, Index{af}, IsArray{0}, MetaFlag{1}
    //          int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{b0}, IsArray{0}, MetaFlag{1}
    //          int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{b1}, IsArray{0}, MetaFlag{1}
    //  float m_SampleRate // ByteOffset{54}, ByteSize{4}, Index{b2}, IsArray{0}, MetaFlag{0}
    //  int m_WrapMode // ByteOffset{5c}, ByteSize{4}, Index{b3}, IsArray{0}, MetaFlag{0}
    //  AABB m_Bounds // ByteOffset{fc}, ByteSize{18}, Index{b4}, IsArray{0}, MetaFlag{0}
    //    Vector3f m_Center // ByteOffset{fc}, ByteSize{c}, Index{b5}, IsArray{0}, MetaFlag{200000}
    //      float x // ByteOffset{fc}, ByteSize{4}, Index{b6}, IsArray{0}, MetaFlag{200000}
    //      float y // ByteOffset{100}, ByteSize{4}, Index{b7}, IsArray{0}, MetaFlag{200000}
    //      float z // ByteOffset{104}, ByteSize{4}, Index{b8}, IsArray{0}, MetaFlag{200000}
    //    Vector3f m_Extent // ByteOffset{108}, ByteSize{c}, Index{b9}, IsArray{0}, MetaFlag{200000}
    //      float x // ByteOffset{108}, ByteSize{4}, Index{ba}, IsArray{0}, MetaFlag{200000}
    //      float y // ByteOffset{10c}, ByteSize{4}, Index{bb}, IsArray{0}, MetaFlag{200000}
    //      float z // ByteOffset{110}, ByteSize{4}, Index{bc}, IsArray{0}, MetaFlag{200000}
    //  unsigned int m_MuscleClipSize // ByteOffset{c8}, ByteSize{4}, Index{bd}, IsArray{0}, MetaFlag{0}
    //  ClipMuscleConstant m_MuscleClip // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{be}, IsArray{0}, MetaFlag{8000}
    //    HumanPose m_DeltaPose // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{bf}, IsArray{0}, MetaFlag{0}
    //      xform m_RootX // ByteOffset{ffffffff}, ByteSize{30}, Index{c0}, IsArray{0}, MetaFlag{0}
    //        float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{c1}, IsArray{0}, MetaFlag{0}
    //          float x // ByteOffset{ffffffff}, ByteSize{4}, Index{c2}, IsArray{0}, MetaFlag{0}
    //          float y // ByteOffset{ffffffff}, ByteSize{4}, Index{c3}, IsArray{0}, MetaFlag{0}
    //          float z // ByteOffset{ffffffff}, ByteSize{4}, Index{c4}, IsArray{0}, MetaFlag{0}
    //          float w // ByteOffset{ffffffff}, ByteSize{4}, Index{c5}, IsArray{0}, MetaFlag{0}
    //        float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{c6}, IsArray{0}, MetaFlag{0}
    //          float x // ByteOffset{ffffffff}, ByteSize{4}, Index{c7}, IsArray{0}, MetaFlag{0}
    //          float y // ByteOffset{ffffffff}, ByteSize{4}, Index{c8}, IsArray{0}, MetaFlag{0}
    //          float z // ByteOffset{ffffffff}, ByteSize{4}, Index{c9}, IsArray{0}, MetaFlag{0}
    //          float w // ByteOffset{ffffffff}, ByteSize{4}, Index{ca}, IsArray{0}, MetaFlag{0}
    //        float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{cb}, IsArray{0}, MetaFlag{0}
    //          float x // ByteOffset{ffffffff}, ByteSize{4}, Index{cc}, IsArray{0}, MetaFlag{0}
    //          float y // ByteOffset{ffffffff}, ByteSize{4}, Index{cd}, IsArray{0}, MetaFlag{0}
    //          float z // ByteOffset{ffffffff}, ByteSize{4}, Index{ce}, IsArray{0}, MetaFlag{0}
    //          float w // ByteOffset{ffffffff}, ByteSize{4}, Index{cf}, IsArray{0}, MetaFlag{0}
    //      float4 m_LookAtPosition // ByteOffset{ffffffff}, ByteSize{10}, Index{d0}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{d1}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{d2}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{d3}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{d4}, IsArray{0}, MetaFlag{0}
    //      float4 m_LookAtWeight // ByteOffset{ffffffff}, ByteSize{10}, Index{d5}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{d6}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{d7}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{d8}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{d9}, IsArray{0}, MetaFlag{0}
    //      staticvector m_GoalArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{da}, IsArray{0}, MetaFlag{0}
    //        Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{db}, IsArray{1}, MetaFlag{0}
    //          int size // ByteOffset{ffffffff}, ByteSize{4}, Index{dc}, IsArray{0}, MetaFlag{0}
    //          HumanGoal data // ByteOffset{ffffffff}, ByteSize{38}, Index{dd}, IsArray{0}, MetaFlag{0}
    //            xform m_X // ByteOffset{ffffffff}, ByteSize{30}, Index{de}, IsArray{0}, MetaFlag{0}
    //              float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{df}, IsArray{0}, MetaFlag{0}
    //                float x // ByteOffset{ffffffff}, ByteSize{4}, Index{e0}, IsArray{0}, MetaFlag{0}
    //                float y // ByteOffset{ffffffff}, ByteSize{4}, Index{e1}, IsArray{0}, MetaFlag{0}
    //                float z // ByteOffset{ffffffff}, ByteSize{4}, Index{e2}, IsArray{0}, MetaFlag{0}
    //                float w // ByteOffset{ffffffff}, ByteSize{4}, Index{e3}, IsArray{0}, MetaFlag{0}
    //              float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{e4}, IsArray{0}, MetaFlag{0}
    //                float x // ByteOffset{ffffffff}, ByteSize{4}, Index{e5}, IsArray{0}, MetaFlag{0}
    //                float y // ByteOffset{ffffffff}, ByteSize{4}, Index{e6}, IsArray{0}, MetaFlag{0}
    //                float z // ByteOffset{ffffffff}, ByteSize{4}, Index{e7}, IsArray{0}, MetaFlag{0}
    //                float w // ByteOffset{ffffffff}, ByteSize{4}, Index{e8}, IsArray{0}, MetaFlag{0}
    //              float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{e9}, IsArray{0}, MetaFlag{0}
    //                float x // ByteOffset{ffffffff}, ByteSize{4}, Index{ea}, IsArray{0}, MetaFlag{0}
    //                float y // ByteOffset{ffffffff}, ByteSize{4}, Index{eb}, IsArray{0}, MetaFlag{0}
    //                float z // ByteOffset{ffffffff}, ByteSize{4}, Index{ec}, IsArray{0}, MetaFlag{0}
    //                float w // ByteOffset{ffffffff}, ByteSize{4}, Index{ed}, IsArray{0}, MetaFlag{0}
    //            float m_WeightT // ByteOffset{ffffffff}, ByteSize{4}, Index{ee}, IsArray{0}, MetaFlag{0}
    //            float m_WeightR // ByteOffset{ffffffff}, ByteSize{4}, Index{ef}, IsArray{0}, MetaFlag{0}
    //      HandPose m_LeftHandPose // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{f0}, IsArray{0}, MetaFlag{0}
    //        xform m_GrabX // ByteOffset{ffffffff}, ByteSize{30}, Index{f1}, IsArray{0}, MetaFlag{0}
    //          float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{f2}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{f3}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{f4}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{f5}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{f6}, IsArray{0}, MetaFlag{0}
    //          float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{f7}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{f8}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{f9}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{fa}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{fb}, IsArray{0}, MetaFlag{0}
    //          float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{fc}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{fd}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{fe}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{ff}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{100}, IsArray{0}, MetaFlag{0}
    //        staticvector m_DoFArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{101}, IsArray{0}, MetaFlag{0}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{102}, IsArray{1}, MetaFlag{0}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{103}, IsArray{0}, MetaFlag{0}
    //            float data // ByteOffset{ffffffff}, ByteSize{4}, Index{104}, IsArray{0}, MetaFlag{0}
    //        float m_Override // ByteOffset{ffffffff}, ByteSize{4}, Index{105}, IsArray{0}, MetaFlag{0}
    //        float m_CloseOpen // ByteOffset{ffffffff}, ByteSize{4}, Index{106}, IsArray{0}, MetaFlag{0}
    //        float m_InOut // ByteOffset{ffffffff}, ByteSize{4}, Index{107}, IsArray{0}, MetaFlag{0}
    //        float m_Grab // ByteOffset{ffffffff}, ByteSize{4}, Index{108}, IsArray{0}, MetaFlag{0}
    //      HandPose m_RightHandPose // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{109}, IsArray{0}, MetaFlag{0}
    //        xform m_GrabX // ByteOffset{ffffffff}, ByteSize{30}, Index{10a}, IsArray{0}, MetaFlag{0}
    //          float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{10b}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{10c}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{10d}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{10e}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{10f}, IsArray{0}, MetaFlag{0}
    //          float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{110}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{111}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{112}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{113}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{114}, IsArray{0}, MetaFlag{0}
    //          float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{115}, IsArray{0}, MetaFlag{0}
    //            float x // ByteOffset{ffffffff}, ByteSize{4}, Index{116}, IsArray{0}, MetaFlag{0}
    //            float y // ByteOffset{ffffffff}, ByteSize{4}, Index{117}, IsArray{0}, MetaFlag{0}
    //            float z // ByteOffset{ffffffff}, ByteSize{4}, Index{118}, IsArray{0}, MetaFlag{0}
    //            float w // ByteOffset{ffffffff}, ByteSize{4}, Index{119}, IsArray{0}, MetaFlag{0}
    //        staticvector m_DoFArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{11a}, IsArray{0}, MetaFlag{0}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{11b}, IsArray{1}, MetaFlag{0}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{11c}, IsArray{0}, MetaFlag{0}
    //            float data // ByteOffset{ffffffff}, ByteSize{4}, Index{11d}, IsArray{0}, MetaFlag{0}
    //        float m_Override // ByteOffset{ffffffff}, ByteSize{4}, Index{11e}, IsArray{0}, MetaFlag{0}
    //        float m_CloseOpen // ByteOffset{ffffffff}, ByteSize{4}, Index{11f}, IsArray{0}, MetaFlag{0}
    //        float m_InOut // ByteOffset{ffffffff}, ByteSize{4}, Index{120}, IsArray{0}, MetaFlag{0}
    //        float m_Grab // ByteOffset{ffffffff}, ByteSize{4}, Index{121}, IsArray{0}, MetaFlag{0}
    //      staticvector m_DoFArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{122}, IsArray{0}, MetaFlag{0}
    //        Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{123}, IsArray{1}, MetaFlag{0}
    //          int size // ByteOffset{ffffffff}, ByteSize{4}, Index{124}, IsArray{0}, MetaFlag{0}
    //          float data // ByteOffset{ffffffff}, ByteSize{4}, Index{125}, IsArray{0}, MetaFlag{0}
    //    xform m_StartX // ByteOffset{ffffffff}, ByteSize{30}, Index{126}, IsArray{0}, MetaFlag{0}
    //      float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{127}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{128}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{129}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{12a}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{12b}, IsArray{0}, MetaFlag{0}
    //      float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{12c}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{12d}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{12e}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{12f}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{130}, IsArray{0}, MetaFlag{0}
    //      float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{131}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{132}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{133}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{134}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{135}, IsArray{0}, MetaFlag{0}
    //    xform m_LeftFootStartX // ByteOffset{ffffffff}, ByteSize{30}, Index{136}, IsArray{0}, MetaFlag{0}
    //      float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{137}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{138}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{139}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{13a}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{13b}, IsArray{0}, MetaFlag{0}
    //      float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{13c}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{13d}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{13e}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{13f}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{140}, IsArray{0}, MetaFlag{0}
    //      float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{141}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{142}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{143}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{144}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{145}, IsArray{0}, MetaFlag{0}
    //    xform m_RightFootStartX // ByteOffset{ffffffff}, ByteSize{30}, Index{146}, IsArray{0}, MetaFlag{0}
    //      float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{147}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{148}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{149}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{14a}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{14b}, IsArray{0}, MetaFlag{0}
    //      float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{14c}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{14d}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{14e}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{14f}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{150}, IsArray{0}, MetaFlag{0}
    //      float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{151}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{152}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{153}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{154}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{155}, IsArray{0}, MetaFlag{0}
    //    xform m_MotionStartX // ByteOffset{ffffffff}, ByteSize{30}, Index{156}, IsArray{0}, MetaFlag{0}
    //      float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{157}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{158}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{159}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{15a}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{15b}, IsArray{0}, MetaFlag{0}
    //      float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{15c}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{15d}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{15e}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{15f}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{160}, IsArray{0}, MetaFlag{0}
    //      float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{161}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{162}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{163}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{164}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{165}, IsArray{0}, MetaFlag{0}
    //    xform m_MotionStopX // ByteOffset{ffffffff}, ByteSize{30}, Index{166}, IsArray{0}, MetaFlag{0}
    //      float4 t // ByteOffset{ffffffff}, ByteSize{10}, Index{167}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{168}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{169}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{16a}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{16b}, IsArray{0}, MetaFlag{0}
    //      float4 q // ByteOffset{ffffffff}, ByteSize{10}, Index{16c}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{16d}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{16e}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{16f}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{170}, IsArray{0}, MetaFlag{0}
    //      float4 s // ByteOffset{ffffffff}, ByteSize{10}, Index{171}, IsArray{0}, MetaFlag{0}
    //        float x // ByteOffset{ffffffff}, ByteSize{4}, Index{172}, IsArray{0}, MetaFlag{0}
    //        float y // ByteOffset{ffffffff}, ByteSize{4}, Index{173}, IsArray{0}, MetaFlag{0}
    //        float z // ByteOffset{ffffffff}, ByteSize{4}, Index{174}, IsArray{0}, MetaFlag{0}
    //        float w // ByteOffset{ffffffff}, ByteSize{4}, Index{175}, IsArray{0}, MetaFlag{0}
    //    float4 m_AverageSpeed // ByteOffset{ffffffff}, ByteSize{10}, Index{176}, IsArray{0}, MetaFlag{0}
    //      float x // ByteOffset{ffffffff}, ByteSize{4}, Index{177}, IsArray{0}, MetaFlag{0}
    //      float y // ByteOffset{ffffffff}, ByteSize{4}, Index{178}, IsArray{0}, MetaFlag{0}
    //      float z // ByteOffset{ffffffff}, ByteSize{4}, Index{179}, IsArray{0}, MetaFlag{0}
    //      float w // ByteOffset{ffffffff}, ByteSize{4}, Index{17a}, IsArray{0}, MetaFlag{0}
    //    OffsetPtr m_Clip // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{17b}, IsArray{0}, MetaFlag{0}
    //      Clip data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{17c}, IsArray{0}, MetaFlag{0}
    //        StreamedClip m_StreamedClip // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{17d}, IsArray{0}, MetaFlag{0}
    //          vector data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{17e}, IsArray{0}, MetaFlag{0}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{17f}, IsArray{1}, MetaFlag{0}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{180}, IsArray{0}, MetaFlag{0}
    //              unsigned int data // ByteOffset{ffffffff}, ByteSize{4}, Index{181}, IsArray{0}, MetaFlag{0}
    //          unsigned int curveCount // ByteOffset{ffffffff}, ByteSize{4}, Index{182}, IsArray{0}, MetaFlag{0}
    //        DenseClip m_DenseClip // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{183}, IsArray{0}, MetaFlag{0}
    //          int m_FrameCount // ByteOffset{ffffffff}, ByteSize{4}, Index{184}, IsArray{0}, MetaFlag{0}
    //          unsigned int m_CurveCount // ByteOffset{ffffffff}, ByteSize{4}, Index{185}, IsArray{0}, MetaFlag{0}
    //          float m_SampleRate // ByteOffset{ffffffff}, ByteSize{4}, Index{186}, IsArray{0}, MetaFlag{0}
    //          float m_BeginTime // ByteOffset{ffffffff}, ByteSize{4}, Index{187}, IsArray{0}, MetaFlag{0}
    //          vector m_SampleArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{188}, IsArray{0}, MetaFlag{0}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{189}, IsArray{1}, MetaFlag{0}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{18a}, IsArray{0}, MetaFlag{0}
    //              float data // ByteOffset{ffffffff}, ByteSize{4}, Index{18b}, IsArray{0}, MetaFlag{0}
    //        ConstantClip m_ConstantClip // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{18c}, IsArray{0}, MetaFlag{0}
    //          vector data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{18d}, IsArray{0}, MetaFlag{0}
    //            Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{18e}, IsArray{1}, MetaFlag{0}
    //              int size // ByteOffset{ffffffff}, ByteSize{4}, Index{18f}, IsArray{0}, MetaFlag{0}
    //              float data // ByteOffset{ffffffff}, ByteSize{4}, Index{190}, IsArray{0}, MetaFlag{0}
    //        OffsetPtr m_Binding // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{191}, IsArray{0}, MetaFlag{0}
    //          ValueArrayConstant data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{192}, IsArray{0}, MetaFlag{0}
    //            vector m_ValueArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{193}, IsArray{0}, MetaFlag{0}
    //              Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{194}, IsArray{1}, MetaFlag{0}
    //                int size // ByteOffset{ffffffff}, ByteSize{4}, Index{195}, IsArray{0}, MetaFlag{0}
    //                ValueConstant data // ByteOffset{ffffffff}, ByteSize{10}, Index{196}, IsArray{0}, MetaFlag{0}
    //                  unsigned int m_ID // ByteOffset{ffffffff}, ByteSize{4}, Index{197}, IsArray{0}, MetaFlag{0}
    //                  unsigned int m_TypeID // ByteOffset{ffffffff}, ByteSize{4}, Index{198}, IsArray{0}, MetaFlag{0}
    //                  unsigned int m_Type // ByteOffset{ffffffff}, ByteSize{4}, Index{199}, IsArray{0}, MetaFlag{0}
    //                  unsigned int m_Index // ByteOffset{ffffffff}, ByteSize{4}, Index{19a}, IsArray{0}, MetaFlag{0}
    //    float m_StartTime // ByteOffset{ffffffff}, ByteSize{4}, Index{19b}, IsArray{0}, MetaFlag{0}
    //    float m_StopTime // ByteOffset{ffffffff}, ByteSize{4}, Index{19c}, IsArray{0}, MetaFlag{0}
    //    float m_OrientationOffsetY // ByteOffset{ffffffff}, ByteSize{4}, Index{19d}, IsArray{0}, MetaFlag{0}
    //    float m_Level // ByteOffset{ffffffff}, ByteSize{4}, Index{19e}, IsArray{0}, MetaFlag{0}
    //    float m_CycleOffset // ByteOffset{ffffffff}, ByteSize{4}, Index{19f}, IsArray{0}, MetaFlag{0}
    //    float m_AverageAngularSpeed // ByteOffset{ffffffff}, ByteSize{4}, Index{1a0}, IsArray{0}, MetaFlag{0}
    //    staticvector m_IndexArray // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1a1}, IsArray{0}, MetaFlag{0}
    //      Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1a2}, IsArray{1}, MetaFlag{0}
    //        int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1a3}, IsArray{0}, MetaFlag{0}
    //        int data // ByteOffset{ffffffff}, ByteSize{4}, Index{1a4}, IsArray{0}, MetaFlag{0}
    //    vector m_ValueArrayDelta // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1a5}, IsArray{0}, MetaFlag{0}
    //      Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1a6}, IsArray{1}, MetaFlag{0}
    //        int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1a7}, IsArray{0}, MetaFlag{0}
    //        ValueDelta data // ByteOffset{ffffffff}, ByteSize{8}, Index{1a8}, IsArray{0}, MetaFlag{0}
    //          float m_Start // ByteOffset{ffffffff}, ByteSize{4}, Index{1a9}, IsArray{0}, MetaFlag{0}
    //          float m_Stop // ByteOffset{ffffffff}, ByteSize{4}, Index{1aa}, IsArray{0}, MetaFlag{0}
    //    bool m_Mirror // ByteOffset{ffffffff}, ByteSize{1}, Index{1ab}, IsArray{0}, MetaFlag{0}
    //    bool m_LoopTime // ByteOffset{ffffffff}, ByteSize{1}, Index{1ac}, IsArray{0}, MetaFlag{0}
    //    bool m_LoopBlend // ByteOffset{ffffffff}, ByteSize{1}, Index{1ad}, IsArray{0}, MetaFlag{0}
    //    bool m_LoopBlendOrientation // ByteOffset{ffffffff}, ByteSize{1}, Index{1ae}, IsArray{0}, MetaFlag{0}
    //    bool m_LoopBlendPositionY // ByteOffset{ffffffff}, ByteSize{1}, Index{1af}, IsArray{0}, MetaFlag{0}
    //    bool m_LoopBlendPositionXZ // ByteOffset{ffffffff}, ByteSize{1}, Index{1b0}, IsArray{0}, MetaFlag{0}
    //    bool m_KeepOriginalOrientation // ByteOffset{ffffffff}, ByteSize{1}, Index{1b1}, IsArray{0}, MetaFlag{0}
    //    bool m_KeepOriginalPositionY // ByteOffset{ffffffff}, ByteSize{1}, Index{1b2}, IsArray{0}, MetaFlag{0}
    //    bool m_KeepOriginalPositionXZ // ByteOffset{ffffffff}, ByteSize{1}, Index{1b3}, IsArray{0}, MetaFlag{0}
    //    bool m_HeightFromFeet // ByteOffset{ffffffff}, ByteSize{1}, Index{1b4}, IsArray{0}, MetaFlag{4000}
    //  AnimationClipBindingConstant m_ClipBindingConstant // ByteOffset{cc}, ByteSize{ffffffff}, Index{1b5}, IsArray{0}, MetaFlag{0}
    //    vector genericBindings // ByteOffset{cc}, ByteSize{ffffffff}, Index{1b6}, IsArray{0}, MetaFlag{0}
    //      Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1b7}, IsArray{1}, MetaFlag{0}
    //        int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1b8}, IsArray{0}, MetaFlag{0}
    //        GenericBinding data // ByteOffset{ffffffff}, ByteSize{14}, Index{1b9}, IsArray{0}, MetaFlag{0}
    //          unsigned int path // ByteOffset{ffffffff}, ByteSize{4}, Index{1ba}, IsArray{0}, MetaFlag{0}
    //          unsigned int attribute // ByteOffset{ffffffff}, ByteSize{4}, Index{1bb}, IsArray{0}, MetaFlag{0}
    //          PPtr<Object> script // ByteOffset{ffffffff}, ByteSize{8}, Index{1bc}, IsArray{0}, MetaFlag{0}
    //            int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{1bd}, IsArray{0}, MetaFlag{1}
    //            int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{1be}, IsArray{0}, MetaFlag{1}
    //          UInt16 classID // ByteOffset{ffffffff}, ByteSize{2}, Index{1bf}, IsArray{0}, MetaFlag{0}
    //          UInt8 customType // ByteOffset{ffffffff}, ByteSize{1}, Index{1c0}, IsArray{0}, MetaFlag{0}
    //          UInt8 isPPtrCurve // ByteOffset{ffffffff}, ByteSize{1}, Index{1c1}, IsArray{0}, MetaFlag{0}
    //    vector pptrCurveMapping // ByteOffset{e0}, ByteSize{ffffffff}, Index{1c2}, IsArray{0}, MetaFlag{0}
    //      Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1c3}, IsArray{1}, MetaFlag{0}
    //        int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1c4}, IsArray{0}, MetaFlag{0}
    //        PPtr<Object> data // ByteOffset{ffffffff}, ByteSize{8}, Index{1c5}, IsArray{0}, MetaFlag{0}
    //          int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{1c6}, IsArray{0}, MetaFlag{1}
    //          int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{1c7}, IsArray{0}, MetaFlag{1}
    //  vector m_Events // ByteOffset{b0}, ByteSize{ffffffff}, Index{1c8}, IsArray{0}, MetaFlag{8001}
    //    Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1c9}, IsArray{1}, MetaFlag{8001}
    //      int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1ca}, IsArray{0}, MetaFlag{1}
    //      AnimationEvent data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1cb}, IsArray{0}, MetaFlag{8001}
    //        float time // ByteOffset{ffffffff}, ByteSize{4}, Index{1cc}, IsArray{0}, MetaFlag{1}
    //        string functionName // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1cd}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1ce}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1cf}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{1d0}, IsArray{0}, MetaFlag{1}
    //        string data // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1d1}, IsArray{0}, MetaFlag{8001}
    //          Array Array // ByteOffset{ffffffff}, ByteSize{ffffffff}, Index{1d2}, IsArray{1}, MetaFlag{4001}
    //            int size // ByteOffset{ffffffff}, ByteSize{4}, Index{1d3}, IsArray{0}, MetaFlag{1}
    //            char data // ByteOffset{ffffffff}, ByteSize{1}, Index{1d4}, IsArray{0}, MetaFlag{1}
    //        PPtr<Object> objectReferenceParameter // ByteOffset{ffffffff}, ByteSize{8}, Index{1d5}, IsArray{0}, MetaFlag{1}
    //          int m_FileID // ByteOffset{ffffffff}, ByteSize{4}, Index{1d6}, IsArray{0}, MetaFlag{1}
    //          int m_PathID // ByteOffset{ffffffff}, ByteSize{4}, Index{1d7}, IsArray{0}, MetaFlag{1}
    //        float floatParameter // ByteOffset{ffffffff}, ByteSize{4}, Index{1d8}, IsArray{0}, MetaFlag{1}
    //        int intParameter // ByteOffset{ffffffff}, ByteSize{4}, Index{1d9}, IsArray{0}, MetaFlag{1}
    //        int messageOptions // ByteOffset{ffffffff}, ByteSize{4}, Index{1da}, IsArray{0}, MetaFlag{1}

    public class AnimationClip : Motion
    {
        public AnimationClip(int version, long dataOffset) : base(version, dataOffset) { }
        public override string GetTypeName() { return "AnimationClip"; }
    }
}
